#! configuration/base.yaml

application:
  port: 8000
database: 
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  timeout_milliseconds: 10000 # 10 second timeout
  authorization_token: "placeholder" # this will be overwritten by DO secret