#! configuration/production.yaml

application:
  host: 0.0.0.0

database:
  # Require SSL for production instances
  require_ssl: true
email_client:
  # From postmark's API docs: 
  base_url: "https://api.postmarkapp.com/email"
  sender_email: "something@gmail.com"